version: "3"

services:
  suno-api:
    build:
      context: .
    volumes:
      - ./public:/app/public
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/suno_db?schema=public
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=suno_db
      - SUNO_COOKIES=${SUNO_COOKIES}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=suno_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
